/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;
/**
 *
 * @author Acer
 */
public class anggota extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet res;
    PreparedStatement st;
    
    private void loaddata(){
    DefaultTableModel t=new DefaultTableModel();
    t.addColumn("NIM");
    t.addColumn("Nama");
    t.addColumn("TTL");
    t.addColumn("Jenis Kelamin");
    t.addColumn("Alamat");
    t.addColumn("Prodi");
    tabel.setModel (t);
    try{ res=stat.executeQuery("select*from anggota");
    while (res.next()){
        t.addRow(new Object []
        { res.getString("NIM"),
            res.getString("Nama"),
            res.getString("TTL"),
            res.getString("Jenis_Kelamin"),
            res.getString("Alamat"),
            res.getString("Prodi")
        });
    }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
    }
}

    /**
     * Creates new form anggota
     */
    public anggota() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("Perpustakaan POLKAM");
        setLocationRelativeTo(null);
        koneksi();
        loaddata();
    }
    private void koneksi (){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/database_perpustakaan","root","");
            stat=con.createStatement();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nim = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        ttl = new javax.swing.JTextField();
        jk = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        prodi = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setLayout(null);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabel);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 380, 682, 95);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("Data Anggota");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(297, 19, 121, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 204));
        jLabel2.setText("NIM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(31, 78, 27, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 204));
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(31, 129, 35, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setText("TTL");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(31, 179, 25, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 204));
        jLabel5.setText("Jenis Kelamin");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(31, 243, 88, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 204));
        jLabel6.setText("Alamat\n");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(31, 287, 45, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 204));
        jLabel7.setText("Prodi\n");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(31, 342, 32, 17);
        jPanel1.add(nim);
        nim.setBounds(203, 77, 173, 20);
        jPanel1.add(nama);
        nama.setBounds(203, 128, 173, 20);
        jPanel1.add(ttl);
        ttl.setBounds(203, 178, 173, 20);
        jPanel1.add(jk);
        jk.setBounds(203, 242, 173, 20);
        jPanel1.add(alamat);
        alamat.setBounds(203, 286, 173, 20);
        jPanel1.add(prodi);
        prodi.setBounds(203, 341, 173, 20);

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(476, 76, 65, 23);

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit);
        edit.setBounds(476, 127, 51, 23);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save);
        save.setBounds(476, 177, 57, 23);

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel1.add(refresh);
        refresh.setBounds(583, 76, 71, 23);

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(591, 127, 63, 23);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(603, 177, 51, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/1111.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 20, 680, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
         String x=JOptionPane.showInputDialog(null,"Masukkan Nim!!");
       try {
           String cari = "select * from anggota where NIM='"+x+"'";
           res=stat.executeQuery(cari);
           if(res.next()) {
               System.out.print(res.getString(1));
               JOptionPane.showMessageDialog(null,"Data ditemukan");
               nim.setText(res.getString(1));
               nama.setText(res.getString(2));
               ttl.setText(res.getString(3));
               jk.setText(res.getString(4));
               alamat.setText(res.getString(5));
               prodi.setText(res.getString(6));
           } else {
               JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
           } 
       } catch (Exception e) {
           System.out.print(e);
           JOptionPane.showMessageDialog(null, "Koneksi gagal");
       }
    }                                      

    private void editActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
         int coba = JOptionPane.showConfirmDialog(null, "Yakin untuk mengubah data ini?","Confirmation",JOptionPane.YES_NO_OPTION);
        try {
            String sql ="update anggota set NIm=?, Nama=?,JenisKelamin=?,Alamat=?,Prodi=? where "+"NIM='"+nim.getText()+"'";
            st=con.prepareStatement(sql);
            if(coba==0);
            try {
                st.setString(1,nim.getText());
                st.setString(2,nama.getText());
                st.setString(3,ttl.getText());
                st.setString(4,jk.getText());
                st.setString(5,alamat.getText());
                st.setString(6,prodi.getText());
                JOptionPane.showMessageDialog(null, "Update data sukses");
                loaddata();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Update data gagal"+e);
            }
        } catch (Exception e) {}
    }                                    

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        try {
            String sqlnya = ("insert into anggota values('"
                    +nim.getText()+"','"
                    +nama.getText()+"','"
                    +ttl.getText()+"','"
                    +jk.getText()+"','"
                    +alamat.getText()+"','"
                    +prodi.getText()+"')");
            stat.executeUpdate(sqlnya);
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
            loaddata();
        } catch (Exception e) {
           System.out.print(e);
           JOptionPane.showMessageDialog(null, "Koneksi gagal");
    }                                   
    }                                    

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        nim.setText(null);
        nama.setText(null);
        ttl.setText(null);
        jk.setText(null);
        alamat.setText(null);
        prodi.setText(null);
    }                                       

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String x = nim.getText();
        try {
            String sql="delete from anggota where NIM = '"+x+"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data telah dihapus");
            loaddata();
            nim.setText(null);
            nama.setText(null);
            jk.setText(null);
            alamat.setText(null);
            prodi.setText(null);
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "KOneksi gagal");
        }
    }                                      

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,"Apakah anda ingin keluar?","Yakin",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        { this.dispose();
        new menuutama().show();
        }
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField alamat;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jk;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nim;
    private javax.swing.JTextField prodi;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField ttl;
    // End of variables declaration                   
}
