/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class databuku extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet res;
    PreparedStatement st;
private void loaddata (){
    DefaultTableModel t=new DefaultTableModel();
    t.addColumn("Kode_Buku");
    t.addColumn("Nama_Buku");
    t.addColumn("Nama_Pengarang");
    t.addColumn("Penerbit");
    t.addColumn("Tahun_Terbit");
    tabel1.setModel (t);
    try{ res=stat.executeQuery("select*from data_buku");
    while (res.next()){
        t.addRow(new Object []
        { res.getString("Kode_Buku"),
            res.getString("Nama_Buku"),
            res.getString("Nama_Pengarang"),
            res.getString("Penerbit"),
            res.getString("Tahun_Terbit")
        });
    }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
    }
}
    /**
     * Creates new form databuku
     */
    public databuku() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("Perpustakaan POLKAM");
        initComponents();
        setLocationRelativeTo(null);
        koneksi();
        loaddata();
    }
    private void koneksi (){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/database_perpustakaan","root","");
            stat=con.createStatement();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namabuku = new javax.swing.JTextField();
        kodebuku = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        pengarang = new javax.swing.JTextField();
        penerbit = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        tahunterbit = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setLayout(null);

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 279, 678, 99);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("Data Buku");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(320, 11, 67, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 204));
        jLabel2.setText("Kode Buku");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(45, 53, 69, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 204));
        jLabel3.setText("Nama Buku");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(41, 101, 73, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setText("Pengarang");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(41, 144, 65, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 204));
        jLabel5.setText("Penerbit");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(41, 183, 52, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 204));
        jLabel6.setText("Tahun Terbit");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(41, 230, 80, 17);
        jPanel1.add(namabuku);
        namabuku.setBounds(196, 100, 143, 20);
        jPanel1.add(kodebuku);
        kodebuku.setBounds(196, 52, 143, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(196, 52, 143, 20);
        jPanel1.add(pengarang);
        pengarang.setBounds(196, 143, 143, 20);
        jPanel1.add(penerbit);
        penerbit.setBounds(196, 182, 143, 20);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(452, 66, 65, 23);

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(450, 120, 65, 23);

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(563, 66, 71, 23);

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(560, 120, 71, 23);
        jPanel1.add(tahunterbit);
        tahunterbit.setBounds(196, 229, 143, 20);

        jButton7.setText("Save");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(460, 180, 57, 23);

        jButton8.setText("Exit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(560, 180, 71, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/1111.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 690, 400);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 690, 440);

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String x=JOptionPane.showInputDialog(null, "Masukkan Kode Buku!!");
        try {
            res=stat.executeQuery("select*from data_buku where Kode_Buku ='"+x+"'");
            if(res.next()) {
                System.out.print(res.getString(1));
                JOptionPane.showMessageDialog(null, "Data ditemukan");
                kodebuku.setText(res.getString(1));
                namabuku.setText(res.getString(2));
                pengarang.setText(res.getString(3));
                penerbit.setText(res.getString(4));
                tahunterbit.setText(res.getString(5));
            } else {
                JOptionPane.showMessageDialog(null, "Data ditemukan");
            }
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(null,"Koneksi Gagal");
        }
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        try{
            String sqlnya=("insert into data_buku values ('"
                    +kodebuku.getText()+"','"
                    +namabuku.getText()+"','"
                    +pengarang.getText()+"','"
                    +penerbit.getText()+"','"
                    +tahunterbit.getText()+"')");
            stat.executeQuery(sqlnya);
            JOptionPane.showMessageDialog(null,"Data Tersimpan");
            loaddata();
        } catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null,"Koneksi Gagal");
        }
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int coba=JOptionPane.showConfirmDialog(null,"Yakin untuk mengubah data ini?","Confirmation",JOptionPane.YES_NO_OPTION);
        try{
            String sql="update data_buku set Kode_Buku=?,Nama_Pengarang=?,Penerbit=?,Tahun_Terbit=? where"+"Kode_Buku='"+kodebuku.getText()
                    +"'";
            st=con.prepareStatement(sql);
            if(coba==0){
                try {
                    st.setString(1,kodebuku.getText());
                    st.setString(2,namabuku.getText());
                    st.setString(3,pengarang.getText());
                    st.setString(4,penerbit.getText());
                    st.setString(5,tahunterbit.getText());
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Update data sukses");
                    loaddata();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"Update data gagal"+e);
                }
            }
        } catch (Exception e){}
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        kodebuku.setText(null);
        namabuku.setText(null);
        pengarang.setText(null);
        penerbit.setText(null);
        tahunterbit.setText(null);
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         String x=kodebuku.getText();
        try {
            String sql="delete from peminjam whereKodeBuku='"+x+"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data telah dihapus");
            loaddata();
            kodebuku.setText(null);
            namabuku.setText(null);
            pengarang.setText(null);
            penerbit.setText(null);
            tahunterbit.setText(null);
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null,"Apakah anda ingin keluar ?", "Yakin", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        { this.dispose();
        new menuutama().show();
        }
    }                                        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new databuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField kodebuku;
    private javax.swing.JTextField namabuku;
    private javax.swing.JTextField penerbit;
    private javax.swing.JTextField pengarang;
    private javax.swing.JTable tabel1;
    private javax.swing.JTextField tahunterbit;
    // End of variables declaration                   
}
