/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.Timer;

/**
 *
 * @author Acer
 */
public class transaksi extends javax.swing.JFrame {
Connection conn;
Statement stat;
ResultSet res;
Connection con;
    /**
     * Creates new form transaksi
     */
    public transaksi() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("Perpustakaan POLKAM");
        initComponents();
        koneksi();
        loaddata();
        loaddata1();
        tanggal();
    }
    private void loaddata(){
        DefaultTableModel t= new DefaultTableModel();
        t.addColumn("kode_Buku");
        t.addColumn("Nama_Buku");
        t.addColumn("Nama_Pengarang");
        t.addColumn("Penerbit");
        t.addColumn("Tahun_Terbit");
        tabel1.setModel(t);
        try{ res=stat.executeQuery("Select*from data_buku");
        while (res.next()){
        t.addRow(new Object[]
                { res.getString("Kode_Buku"),
                  res.getString("Nama_Buku"),
                  res.getString("Nama_Pengarang"),
                  res.getString("Penerbit"),
                  res. getString("Tahun_Terbit")
        });   
        }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
}
    private void koneksi (){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1/database_perpustakaan","root","");
            stat=conn.createStatement();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void loaddata1() {
        DefaultTableModel t=new DefaultTableModel();
        t.addColumn("NIM");
        t.addColumn("Nama");
        t.addColumn("KodeBuku");
        t.addColumn("NamaBuku");
        t.addColumn("TanggalPeminjaman");
        t.addColumn("TanggalPengembalian");
        peminjam.setModel (t);
        try { res=stat.executeQuery("Select * from peminjam");
        while (res.next()){
            t.addRow(new Object []
            {res.getString("NIM"),
                res.getString("NAMA"),
                res.getString("KodeBuku"),
                res.getString("NamaBuku"),
                res.getString("TanggalPeminjam"),
                res.getString("TanggalKembali")
            });
        }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    public void tanggal(){
        java.util.Date tglsekarang = new java.util.Date();
        SimpleDateFormat smpdtfmt = new SimpleDateFormat("yyy MMMMMMMMM dd", Locale.getDefault());
        String tanggal = smpdtfmt.format(tglsekarang);
        tglp.setText(tanggal);
        //tglk.setText(tanggal+3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        peminjam = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jlabel1 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        jlabel3 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        jlabel5 = new javax.swing.JLabel();
        jlabel6 = new javax.swing.JLabel();
        nim = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        kodebuku = new javax.swing.JTextField();
        namabuku = new javax.swing.JTextField();
        tglp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        tglk = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setForeground(new java.awt.Color(102, 204, 0));
        jPanel1.setLayout(null);

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(550, 148, 468, 402);

        peminjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(peminjam);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 581, 534, 152);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("Peminjaman Buku");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(234, 34, 145, 22);

        jlabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(255, 204, 204));
        jlabel1.setText("NIM");
        jPanel1.add(jlabel1);
        jlabel1.setBounds(10, 103, 40, 17);

        jlabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(255, 204, 204));
        jlabel2.setText("Nama");
        jPanel1.add(jlabel2);
        jlabel2.setBounds(10, 150, 50, 17);

        jlabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlabel3.setForeground(new java.awt.Color(255, 204, 204));
        jlabel3.setText("KodeBuku");
        jPanel1.add(jlabel3);
        jlabel3.setBounds(10, 210, 80, 20);

        jlabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlabel4.setForeground(new java.awt.Color(255, 204, 204));
        jlabel4.setText("NamaBuku");
        jPanel1.add(jlabel4);
        jlabel4.setBounds(10, 270, 80, 14);

        jlabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlabel5.setForeground(new java.awt.Color(255, 204, 204));
        jlabel5.setText("Tanggal Pinjam");
        jPanel1.add(jlabel5);
        jlabel5.setBounds(0, 340, 110, 20);

        jlabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlabel6.setForeground(new java.awt.Color(255, 204, 204));
        jlabel6.setText("Tanggal Kembali");
        jPanel1.add(jlabel6);
        jlabel6.setBounds(0, 400, 110, 20);
        jPanel1.add(nim);
        nim.setBounds(150, 100, 127, 20);
        jPanel1.add(nama);
        nama.setBounds(150, 150, 127, 20);
        jPanel1.add(kodebuku);
        kodebuku.setBounds(150, 210, 127, 20);
        jPanel1.add(namabuku);
        namabuku.setBounds(150, 270, 127, 20);
        jPanel1.add(tglp);
        tglp.setBounds(150, 340, 127, 20);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(337, 99, 65, 23);

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(337, 162, 51, 23);

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(337, 236, 57, 23);

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel1.add(refresh);
        refresh.setBounds(450, 99, 71, 23);

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(450, 162, 63, 23);

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(450, 236, 51, 23);
        jPanel1.add(tglk);
        tglk.setBounds(150, 400, 127, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Data Peminjaman");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 517, 184, 35);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Data Buku ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(749, 51, 83, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/1111.jpg"))); // NOI18N
        jLabel4.setText("\n");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 550, 510);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String x=JOptionPane.showInputDialog(null, "Masukkan Kode Buku!!");
        try {
            String cari = "select * from peminjam where KodeBuku='"+"'";
            res=stat.executeQuery(cari);
            if(res.next()) {
                System.out.print(res.getString(1));
                JOptionPane.showMessageDialog(null,"Peminjam ditemukan");
                nim.setText(res.getString("NIM"));
                nama.setText(res.getString("Nama"));
                kodebuku.setText(res.getString("KodeBuku"));
                namabuku.setText(res.getString("NamaBuku"));
                tglp.setText(res.getString("Tanggal Pinjam"));
                tglk.setText(res.getString("Tanggal Kembali"));
                loaddata1();
            } else {
                JOptionPane.showMessageDialog(null, "Buku Belum Dipinjam");
            }
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(null,"Koneksi Gagal ");
        }
    }                                        

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        nim.setText(null);
        nama.setText(null);
        kodebuku.setText(null);
        namabuku.setText(null);
        tglp.setText(null);
        tglk.setText(null);
    }                                       

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String x=jlabel3.getText();
        try {
            String sql="delete from peminjam whereKodeBuku='"+x+"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data telah dihapus");
            loaddata1();
            nim.setText(null);
            nama.setText(null);
            kodebuku.setText(null);
            namabuku.setText(null);
            tglp.setText(null);
            tglk.setText(null);
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        try{
            stat.executeUpdate("insert into peminjam values ("
                    +"'"+nim.getText()+"',"
                    +"'"+nama.getText()+"',"
                    +"'"+kodebuku.getText()+"',"
                    +"'"+namabuku.getText()+"',"
                    +"'"+tglp.getText()+"',"
                    +"'"+tglk.getText()+"')");
            loaddata1();
            JOptionPane.showMessageDialog(null,"Berhasil Menyimpan Data");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perintah Salah : "+e);
        }
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null,"Apakah anda ingin keluar ?", "Yakin", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        { this.dispose();
        new menuutama().show();
        }
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JTextField kodebuku;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField namabuku;
    private javax.swing.JTextField nim;
    private javax.swing.JTable peminjam;
    private javax.swing.JButton refresh;
    private javax.swing.JTable tabel1;
    private javax.swing.JTextField tglk;
    private javax.swing.JTextField tglp;
    // End of variables declaration                   
}
